spring:
  profiles:
    active: dev

---

spring:
  profiles: dev

  datasource:
    url: jdbc:postgresql://localhost:5432/spring_db
    username: postgres
    password: dev9182

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

name: spring-data-sample-dev
enviroment: dev

---

spring:
  profiles: test
name: spring-data-sample-test
enviroment: test